severity:
  warning: error

disabled_rules: 
  - trailing_whitespace

sorted_imports:
  enabled: true
  ignore_case: false

opt_in_rules:
  - empty_count

included:
  - HGithubClient

excluded: 
  - Pods
  - Carthage

reporter: "xcode"

